# Audion Windows Tools by Max.mov — Color themes
# Palettes derived from the project's dark / light-sand README PDF themes.
# Order matters: the first theme is the fallback default on first launch.
# Each theme maps Window.Resources brush keys to hex colors; the engine mutates
# the live SolidColorBrush.Color of each key, so every StaticResource updates at once.
@{
    Themes = @(

        # ── Graphite — neutral dark (default) ─────────────────────────────────
        @{
            Id     = 'graphite'
            Name   = 'Graphite'
            IsDark = $true
            Colors = @{
                AppBg          = '#1b1b1d'
                WindowSurface  = '#232325'
                SidebarSurface = '#202022'
                TitlebarBg     = '#101016'
                CardNeutral    = '#2a2a2d'
                CyanFill       = '#1b2a2e'
                CyanBorder     = '#28515a'
                CyanHeader     = '#28515a'
                GreenAccent    = '#2e9fb3'
                GreenDeep      = '#176675'
                AmberAccent    = '#c75b31'
                AmberBright    = '#e97843'
                AmberDeep      = '#742d1c'
                AmberCardBg    = '#30211d'
                AmberPillBg    = '#421f14'
                SandAccent     = '#b8874b'
                SandBright     = '#d6ad70'
                SandDeep       = '#634826'
                SandCardBg     = '#2d271f'
                SandBorder     = '#785b39'
                SandBtnBg      = '#3c2e1d'
                SandBtnText    = '#ecd3a4'
                BadgeBg        = '#14301f'
                BadgeBorder    = '#235c3a'
                BadgeText      = '#7cc392'
                TitleText      = '#ededee'
                TitleOnCyan    = '#e6f2ec'
                DescText       = '#b6b6bc'
                DescMuted      = '#b2b2b8'
                SidebarText    = '#d4d4d8'
                SidebarMuted   = '#a8a8af'
                HeaderHint     = '#76767e'
                ToggleOffTrack = '#3a3a40'
                ToggleOffThumb = '#9a9aa2'
                ToggleOnThumb  = '#e0faff'
                ApplyBtnBg     = '#123139'
                ApplyBtnText   = '#bfe6eb'
                ApplyBtnBorder = '#1f6270'
                SecBtnBg       = '#2e2e32'
                SecBtnText     = '#c4c4ca'
                PanelHeaderBg  = '#19191f'
                PanelBodyBg    = '#101016'
                PanelInputBg   = '#0d0d13'
                PanelBorder    = '#30303a'
                PanelLabelText = '#707080'
                LogText        = '#8f8fc4'
                LogTimestampText = '#63637c'
                TerminalText   = '#d4d4df'
                TerminalInputText = '#e5e5ec'
                TerminalCommandText = '#63b6d4'
                TerminalOkText = '#35b0c0'
                TerminalWarnText = '#c6944f'
                TerminalErrorText = '#d86436'
            }
        }

        # ── Teal Night — dark (from dark README PDF) ──────────────────────────
        @{
            Id     = 'teal-night'
            Name   = 'Teal Night'
            IsDark = $true
            Colors = @{
                AppBg          = '#0c1213'
                WindowSurface  = '#10191a'
                SidebarSurface = '#0f1718'
                TitlebarBg     = '#071011'
                CardNeutral    = '#142123'
                CyanFill       = '#102a2c'
                CyanBorder     = '#1f4446'
                CyanHeader     = '#1f4446'
                GreenAccent    = '#31a7ba'
                GreenDeep      = '#176b79'
                AmberAccent    = '#d36335'
                AmberBright    = '#ed8250'
                AmberDeep      = '#79351f'
                AmberCardBg    = '#2c1f1a'
                AmberPillBg    = '#3d2116'
                SandAccent     = '#b98b50'
                SandBright     = '#d9af72'
                SandDeep       = '#654a29'
                SandCardBg     = '#27231c'
                SandBorder     = '#735936'
                SandBtnBg      = '#352a1c'
                SandBtnText    = '#ead2a5'
                BadgeBg        = '#133222'
                BadgeBorder    = '#245f3d'
                BadgeText      = '#7fc696'
                TitleText      = '#dbe8e5'
                TitleOnCyan    = '#d8e6e2'
                DescText       = '#a6bdb9'
                DescMuted      = '#93aaa6'
                SidebarText    = '#c2d4d0'
                SidebarMuted   = '#93aaa6'
                HeaderHint     = '#5f7572'
                ToggleOffTrack = '#24383a'
                ToggleOffThumb = '#8fa7a3'
                ToggleOnThumb  = '#e0fbff'
                ApplyBtnBg     = '#0f3038'
                ApplyBtnText   = '#bee7ec'
                ApplyBtnBorder = '#1c6170'
                SecBtnBg       = '#16292b'
                SecBtnText     = '#b0c4c0'
                PanelHeaderBg  = '#0c1516'
                PanelBodyBg    = '#071011'
                PanelInputBg   = '#050c0d'
                PanelBorder    = '#24383a'
                PanelLabelText = '#5f7572'
                LogText        = '#89aaa5'
                LogTimestampText = '#4f6764'
                TerminalText   = '#c9d9d6'
                TerminalInputText = '#d9e7e4'
                TerminalCommandText = '#64b8cc'
                TerminalOkText = '#36afc0'
                TerminalWarnText = '#c59552'
                TerminalErrorText = '#dc693b'
            }
        }

        # ── Slate Blue — cool dark ────────────────────────────────────────────
        @{
            Id     = 'slate-blue'
            Name   = 'Slate Blue'
            IsDark = $true
            Colors = @{
                AppBg          = '#14171c'
                WindowSurface  = '#1b1f26'
                SidebarSurface = '#181c22'
                TitlebarBg     = '#10141a'
                CardNeutral    = '#222730'
                CyanFill       = '#182a3a'
                CyanBorder     = '#2a4256'
                CyanHeader     = '#2a4256'
                GreenAccent    = '#389faf'
                GreenDeep      = '#1d6874'
                AmberAccent    = '#ca6236'
                AmberBright    = '#e27e50'
                AmberDeep      = '#743522'
                AmberCardBg    = '#30231f'
                AmberPillBg    = '#402319'
                SandAccent     = '#b68a52'
                SandBright     = '#d3ac74'
                SandDeep       = '#624a2c'
                SandCardBg     = '#2b271f'
                SandBorder     = '#735a39'
                SandBtnBg      = '#382e20'
                SandBtnText    = '#e9d1a6'
                BadgeBg        = '#163222'
                BadgeBorder    = '#285f40'
                BadgeText      = '#82c399'
                TitleText      = '#dfe4ea'
                TitleOnCyan    = '#dbe6ef'
                DescText       = '#aeb7c3'
                DescMuted      = '#9aa3b0'
                SidebarText    = '#c8d0da'
                SidebarMuted   = '#9aa3b0'
                HeaderHint     = '#6a7280'
                ToggleOffTrack = '#2f3640'
                ToggleOffThumb = '#95a0ae'
                ToggleOnThumb  = '#e7f2fb'
                ApplyBtnBg     = '#103a44'
                ApplyBtnText   = '#bfe3ea'
                ApplyBtnBorder = '#1c5a68'
                SecBtnBg       = '#232934'
                SecBtnText     = '#bcc4d0'
                PanelHeaderBg  = '#171b22'
                PanelBodyBg    = '#10141a'
                PanelInputBg   = '#0c1016'
                PanelBorder    = '#2f3640'
                PanelLabelText = '#6a7280'
                LogText        = '#8d9fba'
                LogTimestampText = '#596473'
                TerminalText   = '#d1d8e2'
                TerminalInputText = '#e0e7f0'
                TerminalCommandText = '#6aaeca'
                TerminalOkText = '#3aa7b7'
                TerminalWarnText = '#bd8e4d'
                TerminalErrorText = '#d4683d'
            }
        }

        # ── Sand — light (from light README PDF) ──────────────────────────────
        @{
            Id     = 'sand'
            Name   = 'Sand'
            IsDark = $false
            Colors = @{
                AppBg          = '#f5eddd'
                WindowSurface  = '#fff8ea'
                SidebarSurface = '#f7efdd'
                TitlebarBg     = '#f3e7d1'
                CardNeutral    = '#fbf3e2'
                CyanFill       = '#d9ebe6'
                CyanBorder     = '#bcd8cf'
                CyanHeader     = '#bcd8cf'
                GreenAccent    = '#176f7d'
                GreenDeep      = '#105661'
                AmberAccent    = '#bd542b'
                AmberBright    = '#9f421f'
                AmberDeep      = '#7d321b'
                AmberCardBg    = '#f3dfd4'
                AmberPillBg    = '#e8c8b7'
                SandAccent     = '#96703a'
                SandBright     = '#745126'
                SandDeep       = '#65461f'
                SandCardBg     = '#f2e7cf'
                SandBorder     = '#cdb386'
                SandBtnBg      = '#ecd9b0'
                SandBtnText    = '#6a4a12'
                BadgeBg        = '#245a38'
                BadgeBorder    = '#183f27'
                BadgeText      = '#e6f5ea'
                TitleText      = '#22312f'
                TitleOnCyan    = '#143028'
                DescText       = '#5a6862'
                DescMuted      = '#66746f'
                SidebarText    = '#2e3c39'
                SidebarMuted   = '#66746f'
                HeaderHint     = '#8a948e'
                ToggleOffTrack = '#d8c9ad'
                ToggleOffThumb = '#fffaf0'
                ToggleOnThumb  = '#ffffff'
                ApplyBtnBg     = '#d2e8ec'
                ApplyBtnText   = '#104f59'
                ApplyBtnBorder = '#83b5be'
                SecBtnBg       = '#efe4cd'
                SecBtnText     = '#4a564f'
                PanelHeaderBg  = '#eadcc1'
                PanelBodyBg    = '#f3e7d1'
                PanelInputBg   = '#eadfc8'
                PanelBorder    = '#d3bd91'
                PanelLabelText = '#8a7a60'
                LogText        = '#4f536b'
                LogTimestampText = '#8a7c62'
                TerminalText   = '#2d3432'
                TerminalInputText = '#26312e'
                TerminalCommandText = '#286f83'
                TerminalOkText = '#176f7d'
                TerminalWarnText = '#8b632e'
                TerminalErrorText = '#a94726'
            }
        }

    )
}
